### ISSUE TITLE
Is MSK_toconic available in the Julia API?

### ISSUE THREAD

**Issue by mtanneau** [MOSEK/Mosek.jl#202]
I cannot find the [`MSK_toconic`](https://docs.mosek.com/9.2/capi/alphabetic-functionalities.html#mosek.task.toconic) function (which is part of the C API) in the Julia wrapper.
Is it possible to add it to this API?

I am trying to compare various approaches for solving MIQPs/MIQCQPs with MOSEK. I'm trying to access to the conic reformulation computed by MOSEK for fair comparison.

**Comment by erling-d-andersen** [comment]
I do not understand the motivation. MOSEK can solve MIQP and MIQCQP directly and that is what a normal users would do.
So why do you need a conic reformulation.

**Comment by mtanneau** [comment]
I am comparing different approaches & formulations for solving MIQPs.
According to the [MOSEK documentation](https://docs.mosek.com/9.2/capi/prob-def-quadratic.html#a-recommendation), MIQPs are converted to conic form before being solved.

For instance, `1/2 x'Qx` can be formulated as `(1, r, Fx) ∈ Qr^{n+2}` if `Q = F'F`.
Obviously, I can do such a reformulation manually, I just want to ensure that I get the same conic form as MOSEK's internal reformulation.

**Comment by erling-d-andersen** [comment]
If you feed the MIQCQP in something close MSK_toconic will be called internally.  If you should do something differently you should rewrite the problem by hand. That means you can be more clever than Mosek can i.e. exploit the ideas outlined in

  https://docs.mosek.com/whitepapers/qmodel.pdf

for instance. 

I would myself always formulate directly on conic form to obtain the best results rather than relying on some automatic procedure. An automatic produce will never be as good as what good human can do.

Btw I am not even sure the MSK_toconic could work in Julia context. Since normally you feed in a problem abnd can then ask for solution. Here you ask of transformation of one problem and to another. It might be possible most likely require quite some work.

**Comment by erling-d-andersen** [comment]
No point in keeping this open.
