### ISSUE TITLE
MOSEK with GitHub action?

### ISSUE THREAD

**Issue by guberger** [MOSEK/Mosek.jl#206]
Would be nice to be able to use the MOSEK solver with GitHub actions. For instance, that a license is not required if MOSEK is used in a workflow launched by a GitHub action. I do not know whether this would be feasible?

**Comment by erling-d-andersen** [comment]
I doubt that is possible.

søn. 18. jul. 2021 13.23 skrev Guillaume Berger ***@***.***>:

**Comment by guberger** [comment]
Ok. Good to know...

**Comment by ulfworsoe** [comment]
This is an issue that has been raised before. It is possible to use most MOSEK functionality without a license by using `optimizermt` instead of optimize with a public MOSEK solver server. `http://solve.mosek.com` is free for problems of limited sizes.

**Comment by guberger** [comment]
@ulfworsoe Thanks for the complemented answer. Is there a way to use the MOSEK solver server with JuMP? If yes, would you have an example where this is done? Thank you!

**Comment by ulfworsoe** [comment]
I think that should be possible. 

When creating the Optimizer, you have to define a fallback optimizer - you can take a look at the tests here: https://github.com/jump-dev/MosekTools.jl/blob/master/test/runtests.jl
I should mention that the `solve.mosek.com` only accepts small problems and imposes a quite short time limit, so it's only really practical for testing and toy-sized problems. I mention this because some of the JuMP test problems turned out to be too large.

**Comment by guberger** [comment]
Thank you very much for the answer! I will try this. Good to know it works only for really small sized problems...
